#Site config
root: /
permalink: /:year-:month/:title/
markdown: kramdown
highlighter: rouge
paginate: 10
title: HackerMi's Blog
description: HakcerMi's Tech & Life 
keywords: HackerMi
url: http://www.hackermi.com
favicon: http://www.hackermi.com/static/favicon.ico
feed: /atom.xml
gems: [jekyll-paginate]

#Author config
author:
  name: HackerMi
  email: hackermi@163.com

#Google Config
google:
  adsense_config: false

