#Site config
root: /
permalink: /:year-:month/:title/
markdown: rdiscount
highlighter: pygments
paginate: 10
title: HackerMi's Blog
description: HakcerMi's Tech & Life 
keywords: HackerMi
url: http://www.hackermi.com
favicon: http://www.hackermi.com/static/favicon.ico
feed: /atom.xml


#Author config
author:
  name: HackerMi
  email: hackermi@163.com

#Google Config
google:
  adsense_config: false

